# Generated by Django 5.2.16 on 2026-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_delivery_status_deliveryattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("suppressed", "Suppressed"),
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("retry_scheduled", "Retry scheduled"),
                ],
                max_length=20,
            ),
        ),
    ]
