# Generated by Django 5.2.16 on 2026-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_delivery_next_attempt_at_alter_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("suppressed", "Suppressed"),
                    ("sent", "Sent"),
                    ("partially_sent", "Partially sent"),
                    ("failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
