# Generated by Django 5.2.16 on 2026-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="dead_lettered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("suppressed", "Suppressed"),
                    ("sent", "Sent"),
                    ("partially_sent", "Partially sent"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
    ]
